os: Visual Studio 2017
# Build 64-bit MSVC binaries on stable, beta and nightly.  I prefer to use the
# native toolchain, ie, MSVC, and 32-bit's dead anyway.
environment:
  target: x86_64-pc-windows-msvc
  matrix:
    - channel: stable
# Install Rust with rustup
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -y --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  # Make nmake available; required by onig-sys dependency (transitive via
  # syntect)
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
build_script:
  - cargo build --release --verbose
after_build:
  # The leading '.\' is important to avoid a command error with -windows being
  # interpreted as flag if APPVEYOR_REPO_TAG_NAME is empty.
  - 7z a .\%APPVEYOR_REPO_TAG_NAME%-windows.zip %APPVEYOR_BUILD_FOLDER%\target\release\mdcat.exe %APPVEYOR_BUILD_FOLDER%\README.md %APPVEYOR_BUILD_FOLDER%\CHANGELOG.md %APPVEYOR_BUILD_FOLDER%\LICENSE
test_script:
  - cargo test --verbose
  - cargo run -- sample/common-mark.md
artifacts:
  - path: '*.zip'
cache:
  - '%USERPROFILE%\.cargo'
  - '%APPVEYOR_BUILD_FOLDER%\target -> Cargo.lock'
