[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less"]
version = "0.11.1-pre"
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]

[badges]
travis-ci = { repository = "lunaryorn/mdcat" }

[features]
default = ["vte50", "iterm2", "terminology"]

resources = ["url"]

# Special terminal features
osc8_links = ["resources"]

# Terminal emulators
iterm2 = ["osc8_links", "resources", "mime", "base64"]
terminology = ["osc8_links", "resources", "immeta"]
vte50 = ["osc8_links"]

[dependencies]
failure = "^0.1"
term_size = "^0.3"
ansi_term = "^0.11"

url = {version = "^1.7", optional = true}
reqwest = {version = "^0.9", optional = true}
mime = {version = "^0.3", optional = true}
base64 = {version = "^0.9", optional = true}
immeta = {version = "^0.4", optional = true}

[dependencies.clap]
version = "^2.32"
default-features = false
features = ["color", "wrap_help"]

[dependencies.pulldown-cmark]
version = "^0.1"
default-features = false
features = []

[dependencies.syntect]
version = "^3"
default-features = false
features = ["parsing", "assets", "dump-load"]

[dev-dependencies]
pretty_assertions = "^0.5"

[package.metadata.release]
sign-commit = true
upload-doc = false
dev-version-ext = "pre"
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-message = "mdcat {{version}}"
tag-prefix = "mdcat-"
pre-release-hook = "./scripts/prerelease-hook.py"
