[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less"]
version = "0.9.3-pre"
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]

[badges]
travis-ci = { repository = "lunaryorn/mdcat" }
maintenance = { status = "actively-developed" }

[features]
default = ["iterm2", "terminology"]

# Enable special support for iTerm2.
iterm2 = ["mime", "base64"]
# Enable special support for Terminology.
terminology = ["immeta"]

[dependencies]
atty = "^0.2"
failure = "^0.1"
reqwest = "^0.8"
term_size = "^0.3"
url = "^1.6"
ansi_term = "^0.11"

mime = {version = "^0.3", optional = true}
base64 = {version = "^0.9", optional = true}
immeta = {version = "^0.4", optional = true}

[dependencies.clap]
version = "^2.29"
default-features = false
features = ["color", "wrap_help", "vec_map"]

[dependencies.pulldown-cmark]
version = "^0.1"
default-features = false
features = []

[dependencies.syntect]
version = "^2"
default-features = false
features = ["parsing", "assets", "dump-load"]

[package.metadata.release]
sign-commit = true
upload-doc = false
dev-version-ext = "pre"
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-message = "mdcat {{version}}"
tag-prefix = "mdcat-"
pre-release-hook = "./scripts/prerelease-hook.py"
