[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less"]
version = "0.13.1-pre"
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2018"

[features]
default = ["remote_resources"]
remote_resources = ["reqwest"]

[dependencies]
ansi_term = "^0.12"
base64 = "^0.11"
failure = "^0.1"
gethostname = "^0.2"
image = "^0.22.2"
mime = "^0.3"
term_size = "^0.3"
url = "^1.7"

# Dependencies for iTerm2 + kitty
# Fetch images over HTTP for iTerm2 + kitty
reqwest = {version = "^0.9", optional = true}

[dependencies.clap]
version = "^2.33"
default-features = false
features = ["color", "wrap_help"]

[dependencies.pulldown-cmark]
version = "^0.6"
default-features = false
features = ['simd']

[dependencies.syntect]
# onig rust fails to build w/o clang currently so pin syntect,
# see <https://github.com/rust-onig/rust-onig/issues/109> and GH-90
version = "^3, <3.2"
default-features = false
features = ["parsing", "assets", "dump-load"]

[dev-dependencies]
pretty_assertions = "^0.6"

[package.metadata.release]
upload-doc = false
dev-version-ext = "pre"
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-message = "mdcat {{version}}"
tag-prefix = "mdcat-"
pre-release-hook = "./scripts/prerelease-hook.py"
