[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
documentation = "https://docs.rs/mdcat"
keywords = ["markdown", "less", "cat"]
version = "0.25.1"
categories = ["command-line-utilities", "text-processing"]
license = "MPL-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]
edition = "2021"

[dependencies]
ansi_term = "^0.12"
base64 = "^0.13"
gethostname = "^0.2"
image = "0.24.0"
mime = "^0.3"
url = "^2.2"
fehler = "^1"
anyhow = "^1"
shell-words = "^1"
env_proxy = "^0.4"
ureq = { version = "^2.0", features = ["tls", "native-certs"] }

[dependencies.clap]
version = "^2.33"
default-features = false

[dependencies.pulldown-cmark]
version = "0.9.1"
default-features = false
features = ['simd']

[dependencies.syntect]
version = "^4.5"
default-features = false
features = ["parsing", "assets", "dump-load", "regex-fancy"]

[target.'cfg(unix)'.dependencies]
libc = "^0.2"

[target.'cfg(windows)'.dependencies]
terminal_size = "^0.1"

[dev-dependencies]
pretty_assertions = "^1"
lazy_static = "^1.4"
test-generator = "^0.3"

[build-dependencies]
# To generate completions during build
clap = { version = "^2.33", default-features = false }

[profile.release]
# Enable LTO for release builds; makes the binary a lot smaller
lto = true

[package.metadata.release]
allow-branch = ["main"]
pre-release-commit-message = "Release {{version}}"
post-release-commit-message = "Bump version to {{next_version}}"
tag-prefix = "mdcat-"
tag-name = "{{prefix}}{{version}}"
tag-message = "mdcat {{version}}"
pre-release-replacements = [
    # Update version and release date in manpage
    { file="mdcat.1.adoc", search="(?m)^:revnumber:.*$", replace = ":revnumber: {{version}}" },
    { file="mdcat.1.adoc", search="(?m)^:revdate:.*$", replace = ":revdate: {{date}}" },
    # Update the changelog
    { file="CHANGELOG.md", search="## \\[Unreleased\\]", replace = "## [Unreleased]\n\n## [{{version}}] – {{date}}", exactly = 1 },
    { file="CHANGELOG.md", search="HEAD", replace = "{{tag_name}}", exactly = 1 },
    { file="CHANGELOG.md", search="\\[Unreleased\\]: ", replace = "[Unreleased]: https://github.com/lunaryorn/mdcat/compare/{{tag_name}}...HEAD\n[{{version}}]: ", exactly = 1 },
]
