[package]
name = "mdcat"
description = "cat for markdown: Show markdown documents in terminals"
readme = "README.md"
homepage = "https://github.com/lunaryorn/mdcat"
repository = "https://github.com/lunaryorn/mdcat"
keywords = ["markdown", "less"]
version = "0.5.1-pre"
categories = ["command-line-utilities", "text-processing"]
license = "Apache-2.0"
authors = ["Sebastian Wiesner <sebastian@swsnr.de>"]

[badges]
travis-ci = { repository = "lunaryorn/mdcat" }
maintenance = { status = "actively-developed" }

[dependencies]
clap = "^2.29"
termion = "^1.5"
syntect = "^2"
pulldown-cmark = "^0.1"
base64 = "^0.9"
url = "^1.6"

[package.metadata.release]
sign-commit = true
upload-doc = false
dev-version-ext = "pre"
pre-release-commit-message = "Release {{version}}"
pro-release-commit-message = "Bump version to {{version}}"
tag-message = "mdcat {{version}}"
tag-prefix = "mdcat-"
pre-release-hook = "./scripts/prerelease-hook.py"