name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publishing ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_target: [macos, linux]
        include:
          - build_target: macos
            os: macos-latest
            artifact_suffix: macos-x86_64
            target: x86_64-apple-darwin
            features: ''
          - build_target: linux
            os: ubuntu-latest
            artifact_suffix: linux-x86_64
            target: x86_64-unknown-linux-musl
            features: ''
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
          profile: minimal
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
      - name: Checkout src
        uses: actions/checkout@v2
      - name: Running cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Packaging assets
        shell: bash
        run: |
          cd target/
          ls -la
          cd release
          ls -la
          tar czvf mdcat-${{ matrix.target }}.tar.gz mdcat
          shasum -a 256 mdcat-${{ matrix.target }}.tar.gz > mdcat-${{ matrix.target }}.sha256
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/mdcat-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
